config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'badges/index'
    get 'badges/new'
    get 'badges/create'
    get 'badges/destroy'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { registrations: 'registration', sessions: 'sessions' }

  root 'tests#index'

  resources :badges, only: :index do
    get :my_badges, on: :collection
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get '/contacts', to: 'contacts#new', as: 'contacts'
  post '/contacts', to: 'contacts#submit'
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to gist.unique_hash, "https://gist.github.com/#{gist.unique_hash}" %></td>
  <td><%= link_to truncate(gist.question.body, length: 25), admin_question_path(gist.question) %></td>
  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<div>
  <p>
  <%= link_to t('admin.tests.list'), admin_tests_path %>
  </p>
  <table class="table">
    <tr>
      <th><%= t('admin.gists.id') %></th>
      <th><%= t('admin.gists.title') %></th>
      <th><%= t('admin.gists.user_email') %></th>
    </tr>
    <%= render @gists %>
  </table>
</div>