config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'badges/index'
    get 'badges/new'
    get 'badges/create'
    get 'badges/destroy'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { registrations: 'registration', sessions: 'sessions' }

  root 'tests#index'

  resources :badges, only: :index do
    get :my_badges, on: :collection
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get '/contacts', to: 'contacts#new', as: 'contacts'
  post '/contacts', to: 'contacts#submit'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true
  has_many :test_passages, dependent: :nullify
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  SUCCESS_SCORE = 85

  enum status: {:passing => 1, :passed => 2, :failed => 3}
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true, inverse_of: :test_passages
  has_many :gists

  before_validation :before_validation_set_first_question, on: :create
  after_validation :after_validation_set_next_question, on: :update
  before_create :set_default_status
  before_save :before_save_update_status

  scope :passing, -> {where(status: statuses[:passing])}
  scope :passed, -> {where(status: statuses[:passed])}
  scope :failed, -> {where(status: statuses[:failed])}
  scope :by_level, -> (level) { joins(:test).where(tests: {level: level}) }

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def result
    (correct_questions.to_f / test.questions.count.to_f) * 100
  end

  def current_question_number
    total_questions_count - remaining_questions.count
  end

  def total_questions_count
    test.questions.count
  end

  def success?
    result >= SUCCESS_SCORE ? "pos" : "neg"
  end

  def add_badges
    Badge.find_each do |badge|
      user.badges.push(badge) if badge.suitable?(self)
    end
  end

  def timeout?
    current_time = Time.now.to_i
    seconds = test.timer_value.seconds
    created_time = updated_at.to_i
    (current_time - created_time) - seconds > 0 
  end

  private
  def after_validation_set_next_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    correct_answers_count == correct_answers.where(id: answer_ids).count &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    @correct_answerts ||= current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def remaining_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def set_default_status
    self.status = TestPassage.statuses[:passing]
  end

  def before_save_update_status
    self.status = result >= SUCCESS_SCORE ? TestPassage.statuses[:passed] : TestPassage.statuses[:failed]
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]
  before_action :check_timeout, only: %i[show update]

  def show; end

  def result; end

  def update
    Timeout::timeout(@test_passage.test.timer_value.seconds) do
      @test_passage.accept!(params[:answer_ids])
      if @test_passage.completed?
        TestsMailer.completed_test(@test_passage).deliver_now
        @test_passage.add_badges
        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    rescue Timeout::error
      check_timeout
    end
  end

  def gist
    gist_service = GistQuestionService.new(@test_passage.current_question)
    gist_service.call
    @gist = current_user.gists.new(unique_hash: gist_service.result[:id],
                                   question: @test_passage.current_question)
    flash_options = if gist_service.success? && @gist.save
                      {notice: "#{t('.success')} #{gist_service.result['html_url']}"}
                    else
                      {alert: t('.failure') }
                    end
    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def check_timeout
    if @test_passage.timeout?
      flash[:danger] = "Time is up"
      redirect_to root_url
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<% color = @test_passage.success? %>
<h2> You've finished the test with <div class="<%= color %>"><%= @test_passage.result %></div> success! </h2>
<% if @test_passage.result >= 85 %>
  <h2>You've successfully completed the test!</h2>
<% else %>
  <h2>You've failed the test</h2>
<% end %>

<%= link_to 'Return to tests', tests_path %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>
<p>
<b><%= @test_passage.current_question.body %></b>
</p>
<%= content_tag :p, '', class: 'countdownLabel', data: {seconds: @test_passage.test.timer_value} %>
<b>
  The current question is <%= @test_passage.current_question_number %> / <%= @test_passage.test.questions.count %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= content_tag :div, '',
    class: 'progress', data: {currentNumber: @test_passage.current_question_number, total: @test_passage.test.questions.count} %>

  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :text, include_hidden: false do |b| %>
    <p>
    <%= b.check_box id: "answer_ids_#{b.object.id}" %>
    <%= b.label %>
    </p>
  <% end %>
  <p> <%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p> <%= form.submit 'Next' %> </p>
<% end %>