config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'badges/index'
    get 'badges/new'
    get 'badges/create'
    get 'badges/destroy'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { registrations: 'registration', sessions: 'sessions' }

  root 'tests#index'

  resources :badges, only: :index do
    get :my_badges, on: :collection
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get '/contacts', to: 'contacts#new', as: 'contacts'
  post '/contacts', to: 'contacts#submit'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true
  has_many :test_passages, dependent: :nullify
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_question, only: [:show, :destroy]
  before_action :find_test, only: [:index, :new, :create]

  rescue_from ActiveRecord::RecordNotFound,
    with: :rescue_question_not_found

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @test.questions.create(question_params)
    redirect_to admin_test_url(@test)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to admin_question_path @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    render plain: 'The question was removed from db'
  end

private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_question_not_found
    render plain: 'Question not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    test = Test.find_by(params[:id])

    if question.new_record?
      "Create New #{test.title} Question"
    else
      "Edit #{test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
  <%= form.label :body %>
  <%= form.text_field :body, id: :question_body %>
  </p><br>
  <p>
  <p><%= form.submit %></p>
  </form>
<% end %>

app/views/admin/questions/_question.html.erb
<ul>
  <li><%= question.body %></li>
  <td><%= link_to t('common.show'), admin_question_path(question) %></td>
  <td><%= link_to t('common.edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('common.delete'),
      admin_question_path(question),
      method: :delete,
      data: { confirm: t('common.confirm') } %>
  </td>
</ul>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>
<%= render 'form' %>
<%= link_to t('common.back'), admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>
<%= render 'form' %>
<%= link_to t('common.back'), admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %></h1>

<p><%= @question.body %></p>

<h2><%= t('admin.question.answers') %></h2>
<%= link_to t('admin.question.new_answer'), new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to t('common.edit'), edit_admin_question_path(@question) %> |
<%= link_to t('common.delete'), admin_question_path(@question), :method => :delete %> |
<%= link_to t('common.back'), admin_test_path(@question.test) %>