config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'badges/index'
    get 'badges/new'
    get 'badges/create'
    get 'badges/destroy'
  end
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { registrations: 'registration', sessions: 'sessions' }

  root 'tests#index'

  resources :badges, only: :index do
    get :my_badges, on: :collection
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get '/contacts', to: 'contacts#new', as: 'contacts'
  post '/contacts', to: 'contacts#submit'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="float-left">
      <small>
        <%= t('footer.credentials') %> <%= link_to 'Thinknetica project', "http://thinknetica.com/", target: :_blank %>
      </small>
      <nav>
        <ul>
          <li><%= current_year %></li>
          <li> Rom <%= github_link('drougojrom', 'test-guru') %></li></li>
          <li> <%= link_to 'Contact us', contacts_path %>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand'%>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= link_to 'Admin Panel', admin_tests_path %>
      <% end %>
      <li><%= t('header.welcome') %>, <b><%= current_user.first_name %></b> <%= t('header.guru') %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t('header.dropdown') %><b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to t('header.logout'), destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to "Show badges", my_badges_badges_path %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to t('common.login'), new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Admin Panel | Test Guru</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <% render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=width-device, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>